// const endpoint = "https://dxapi.actiandatacloud.com/"
// const server = ""
// const ePLogin = "https://dxapi.actiandatacloud.com/v2/login"
// const username = "dr.who@test.com"
// const password = "v3ct0R!23"
// const account = "https://dxapi.actiandatacloud.com/v2/account/"
// const jobConfigEndpoint ="https://dxapi.actiandatacloud.com/v2/jobconfigs/"
// const userEndPoint = "https://dxapi.actiandatacloud.com/v2/users/"
// const macrosEndpoint = "https://dxapi.actiandatacloud.com/v2/macrosets/"
// const templatesEndpoint = "https://dxapi.actiandatacloud.com/v2/jobtemplates/"
// const files = "https://dxapi.actiandatacloud.com/v2/files/"

 // URL of API endpoint
 apiURL: 'https://api.im.actiandatacloud.com/v1/api/'
const endpoint = "https://api.im.actiandatacloud.com/"
const server = ""
const ePLogin = "https://api.im.actiandatacloud.com/v1/api/login"
const username = "dr.who@test.com"
const password = "Actian@123"
const account = "https://api.im.actiandatacloud.com/v1/api/account/"
const jobConfigEndpoint ="https://api.im.actiandatacloud.com/v1/api/jobconfigs/"
const userEndPoint = "https://api.im.actiandatacloud.com/v1/api/users/"
const macrosEndpoint = "https://api.im.actiandatacloud.com/v1/api/macros/"
const templatesEndpoint = "https://api.im.actiandatacloud.com/v1/api/jobtemplates/"
const filesEndpoint = "https://api.im.actiandatacloud.com/v1/api/files/"
